= Apt Cache Proxy with Peers Support
Luis Garcia
:compat-mode:
:toc:
:icons: font
:toc-title: Index
:toclevels: 3
:doctype: article
:experimental:
:icons: font
:sectanchors:
:sectlinks:
:sectnums:
:imagesdir: ./images

== Overview

This is the LliureX fork of APT Cache Proxy of felix-homelab (https://github.com/felix-homelab/apt-cache-proxy).

APT Cache Proxy is a lightweight APT caching proxy server written in Python. It caches packages from upstream mirrors to save bandwidth and speed up package installation in local network scenarios. It can be used as drop-in replacement for `apt-cacher-ng` in apt configuration.

link:README-apt-cache-proxy.md[This is the link to the documentation of the original project]

For those nostalgic for the old LliureX classroom model, the APT cache proxy can be seen as an evolution of the old mirror service, adapted for serverless, distributed environments and dynamically built based on requests from clients and other computers on the network.

This new approach provides similar speed and bandwidth savings, without the need for manual maintenance or updates of the mirror.

== LliureX contributions

The main contributions of LliureX to the original code are:

* Peer support
* Zeroconf/Avahi support both to advertise the service and to detect other proxies
* resource-downloader: a generic download tool (no apt related) to get arbitrary files from preconfigured sources using the service as a general purpose proxy with integrity support

== Peer support

This is a new feature to improve performance and reduce bandwith when multiple proxies are available in the same lan.

The main idea is to check whether the packages are available in the cache of other computers on the LAN that are also running the proxy, avoiding the need to download them from upstream mirrors. These neighboring proxies ("peers" in advance) would be detected dynamically and kept in memory at runtime, without persistence.

=== Security
apt provides security mechanisms based on the digital signatures of the "Release" files in the repositories to ensure the authenticity of upstream mirrors.

However, no identity verification is required for peers. To avoid the possibility of evil or corrupted package injection, all the repository metadata (indexes, release files, etc) MUST BE downloaded EXCUSIVELY from original upstream mirrors.

To ensure that inappropriate files are not downloaded from a peer, a comprehensive filter system based on regular expressions has been included.

Filtering rules can be included in the configuration file as a dictionary, named 'peers_blacklist'. The dictionary values are lists ('arrays'), and are used as rules to discard files.
Each key indicates the part of the full pathname of the package file to apply the filter (we use 'stem' and 'suffix' in the same way that Python Pathlib do):

* fullpath: default empty -> []
* name: default -> [ "^Packages(\\.gz){0,1}$", "^Release$", "^InRelease$" ]
* stem: default empty -> []
* suffix: default -> [ "^\\.gpg$", "^\\.md5$", "^\\.sha(\\d){0,3}$" ]





Mechanisms for discovery and detection will also be needed (my idea is to use mDNS via Python Zeroconf). I don't yet have a complete implementation of this part. Furthermore, it wouldn't be essential to include this functionality directly in the apt-cache-proxy code; it could be done through a helper service that interacts with the proxy via the new API.

